<?php require_once 'header-internal.php';?>

		<div id="content" class="site-content about-page">
			<div class="breadcrumb">
				<div class="container">
					<ul>
						<li><a href="index.php">Home</a></li>
						<li><span class="current">Privacy Policy</span></li>
					</ul>
				</div><!-- .container -->
			</div><!-- .breadcrumb -->

			<div class="about-info">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<h2 class="heading-title">Privacy Policy</h2>
							<p>This document is published in accordance with the provisions of Rule 4(1) of the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011 which requires the publishing of a privacy policy for handling of or dealing in personal information including sensitive personal data or information.<br>
							This Site is owned and operated by PriSom Technologies Private Limited, a limited liability partnership incorporated under the provisions of the (Limited Liability Partnership Act, 2008, having its registered office at , India (hereinafter referred to as "Site Owner" "we" "us" or "our").</p>
							
							<p>Any reference to "you" or "your" in this privacy policy ("Privacy Policy"), means you as a user of our site (www.my-dream-wear.com) ("Site") for accessing, browsing, using the Site and placing orders for renting or purchasing the Products (as defined below) listed on the Site ("User"). Products shall mean "products and/or accessories displayed on the Site available to Users to rent or purchase for personal use" ("Products"). The afore-mentioned services provided to the User for browsing and/or renting or purchasing the Products displayed by the Site Owner on the Site, along with other services as may be included and modified from time to time, shall together be referred to as "Services".</p>

							<p>As a User, your access to and use of the Site is conditional upon your acceptance of and continued compliance with this Privacy Policy. By using the Site, you agree to be bound by this Privacy Policy and all rules, guidelines, policies including the cancellation policy, return policy, Terms and Conditions (defined below) applicable to the Services being provided by Site Owner ("Policies"), as may be modified by the Site Owner from time to time, unconditionally and at all times and further agree and confirm that you consent to providing the Site Owner with your personal information for the purpose set out below and you understand that such collection, storage and handling is lawful, necessary and permissible under applicable laws.</p>

							<p><i>Each capitalized term not defined but used in this Privacy Policy shall have the same meaning as ascribed to such term in the Terms and Conditions (defined below).</i></p>
							
							<p><b>Requirement for collection of information</b></p>
							
							<p>The information collected is relevant and necessary to understand you or your online browsing search pattern, including Products searched. The information is collected with an intention to provide you with a customized site experience, provide updated information, provide help regarding usage of the Site or any of our other advertiser-focused websites or new services and special offers we think you might be interested in, carry out follow ups, to assist with customer service or technical support issues, troubleshoot problems, measure gauge for surveys on your interest in the Products displayed on the Site, enforce the Terms and Conditions and other related Policies or to prevent fraud and unlawful use. It may be noted that the Site Owner has strict guidelines with respect to unauthorized access to information provided by the User (as enumerated below).</p>

							<p><b>Collection of Information</b></p>

							<p>Our Privacy Policy contains provisions regarding collection, storage and handling of personal and non-personal information that you share on the Site. These could include mandatory or voluntary disclosures that you make while and for using the Site. Personal Information is data that can be used to uniquely identify or contact a single person ("Personal Information"). Personal Information for the purposes of this Privacy Policy shall include, but not be limited to, your name, address, telephone number, date of birth, gender, e-mail address, images, etc. provided by you whilst using the Site and/ or availing the Services. Kindly note that we will also require your credit card/debit card details for facilitating the payments in relation to the Order placed by you, however such details shall not be stored or used by us in any manner other than in accordance with the Terms and Conditions. Kindly note that the Site Owner uses an online payment gateway operated by third parties and the information that you provide at the time of placing an Order on the Site is held and stored by such third party payment gateway operator. </p>

							<p>By accessing, browsing and continuing to use/browse the Site or by clicking on "Register" or "Submit" icons or other relevant icons/ buttons on the Site, you accept the terms of this Privacy Policy, and the fact that we store and process your Personal Information in accordance with this Privacy Policy.</p>

							<p>If you submit a comment or feedback including images on any Product featured on the Site and/or any of the Services offered on the Site, we may (but are not obliged to) publish your comments/feedback (including images) online or offline to promote our business, Products and Services. We will collect your name which will be displayed next to your comment, and e-mail address, which will not be published, but which we may use to contact you in relation to your comment. From time to time, we may ask you for your opinion on our Products and/or Services. When we do surveys wherein we may use cookies or other on-device storage and may combine the information collected by those cookies or other on-device storage with your answers. We will make sure that the survey results do not identify you, or anyone else who fills in our surveys.</p>

							<p>What we know about you we get mostly from you. But we may also have to find out more about you from other sources in order to verify the information submitted by you, and to make sure that what we know about you is correct and complete. This kind of verification is primarily done in order to address various security concerns, and to ensure that you comply with the provisions of applicable laws, and the terms and conditions available on the Site ("Terms and Conditions") and other terms and conditions as may be prescribed by us from time to time. We do not collect personally identifiable information (including Personal Information) about you, expect when you specifically provide such information on a voluntary basis.</p>

							<p><b>Usage of Information Collected</b></p>

							<p>We are sensitive towards your information including your Personal Information and non-personal information (email, business details, demographic location and address, age, name, phone number etc.,) provided at the time of registering on the Site or otherwise while availing the Services on the Site.<br>
							We use information about you to help us provide you with a more personalized service which is tailored to suit your needs.<br>
							Your Personal Information may be used by us to:<br>
							i.	monitor, develop and improve the Site, Services and your experience;<br>
							ii.	assist in and administer the provision of Services to you;<br>
							iii.	process and deal with any complaints or enquiries made by or about you; and<br>
							iv.	investigate any suspected breach of the Terms and Conditions or the breach of other terms and conditions otherwise relating to you and to monitor compliance including by way of checking postings or submissions to the Site.<br><br>
							You hereby agree and acknowledge that by accessing and browsing the Site, you consent to the Site Owner undertaking the following:<br><br>
							i.	send you and keep you updated with information by email, telephone (including SMS)  or mail about existing and new services and special offers from us;<br>
							ii.	send you information by email, telephone or mail about related products or services of selected third parties that may be of interest to you; and<br>
							iii.	use the information for marketing and for market research purposes, including internal demographic studies, to provide, optimize and personalize our services and to send you newsletters and information about the products and services.<br>
							The information is readily available on the Site and only viewable by you by logging on to the Site. You, at all times have the option not to provide any personal or other information about you without agreeing to register on the Site and otherwise withdrawal your consent by communicating the same to us in the manner in the Terms and Conditions and the Policies. Upon withdrawal, the Site Owner will have no obligations towards you nor will it be liable in relation to any Services rendered by the Site Owner during the time you had consented to retain the information with the Company. Further, in such an event any Product in the possession of a User shall be returned to the Site Owner in accordance with the terms of the Return Policy.<br>
							Please note that if you "do not agree" to, or "opt out" from, providing personal or other information requested by us, you may not be able to access certain areas of the Site and/or avail certain Services. However, it may be noted that the Site Owner reserves the right to send service related and your specific and preferred transaction related communication without offering you the facility to opt-out. You can update your Account Information (defined below), Personal Information and other information at any time. At your request, the Site Owner can also cancel your registration and remove/block your Personal Information from its database/ Site. However, this information may remain in our archive even after deletion or termination of your account as required by law and the handling of the same is in accordance with the provisions of the applicable law and as intimated by the government agency from time to time.</p>
							<p><b>Use of information for marketing</b></p>

							<p>In line with any permission given by you to us, we may send you direct marketing communications about our own, or selected third party services and disclose your information to other organizations who may send direct marketing communications to you. In addition, you can unsubscribe from email communications via unsubscribe links provided in communications sent to you.</p>
							<p><b>Use of Cookies</b></p>
							<p>By using or accessing the Site, our servers (hosted by a third party service provider) may collect information indirectly and automatically about your activities on the Site by way of cookies. Cookies are pieces of information that a site sends to your computer or other media device while you are viewing or interacting with the site. We use cookies and other such devices to compile anonymous, aggregated statistics that allow us to understand how users use our Site and to help us improve the structure of our Site (we cannot identify you personally in this way). Further it allows us to understand who has seen which pages and advertisements on the Site, to determine how frequently particular such pages and advertisements are visited, to determine the most popular areas of the Site and generally in order to monitor usage of the Site. We may combine your visitor session information or other information collected through cookies and other technical methods with personally identifiable information in order to understand and improve your online experiences and to determine what category/nature of businesses and locations you prefer or are likely to be of interest to you. This information is not linked to your Personal Information and is maintained distinctly.<br>
							You may also get cookies from our advertisers. We do not control these cookies, and once you have clicked on the advertisement and left the Site, our Privacy Policy no longer applies. The Site Owner is not responsible for collecting cookies through Linked Sites (defined below), neither is it liable for misuse of the information you provide to Linked Sites.<br>
							It is clarified that we store information including Personal Information only in the manner contained herein and in accordance with the provisions of applicable law.<br>
							You can change your web browsers settings to accept or not to accept cookies. The Site Owner may use third-party service providers to serve ads on its behalf across the internet and sometimes on the Site. Such third party service providers may collect anonymous information about your visits to the Site and the Products displayed on the Site. Personally identifiable information is not linked to data collected from this source.<br>
							The Site could use log file including internet protocol addresses, browser type, internet service provider, referring/exit pages, platform type, date/time stamp, and number of clicks to analyse  trends, administer the Site, track user movement and gather broad demographic information for aggregate use. These are not linked to information identifiable personally.</p>
							<p><b>Information Sharing</b></p>
							<p>For any payments on the Site, the Site Owner uses online payment gateway operated by third party and the information that you provide at the time of placing an Order on the Site is held and stored with third party payment gateway operator authorised at multiple points. The payment gateway operator may also have access to your online payment history/details in relation to the Orders that you place on the Site. These payment gateways are digitally encrypted, thereby providing the highest possible degree of privacy and care available, currently. Whilst we are unable to guarantee 100% (one hundred percent) security, this makes it hard for a hacker to decrypt your details. You are strongly recommended not to send full credit or debit card details in unencrypted electronic communications with us. Also, you are responsible for protecting against un authorised access to your password and to your computer. We will not be liable for the disclosure and dissemination of Personal Information to third parties which you as prudent Users put up on the Site, and available to the other Users of the Site.<br>
							It is hereby clarified that we do not store extremely sensitive information like your credit card/debit card information on our database<br>
							The Site Owner handles all such information in accordance with the provisions of the applicable law as may be applicable from time to time and only for the duration lawfully required, there under. The Company may disclose aggregated information, including to aggregators, about the use of the Site without Personal Information. The Company implements standard measures to protect against unauthorized access to and unlawful interception of Personal Information. However, the Company feels prudent to inform you that no internet site can fully eliminate security risks and enforcement of privacy laws are at a developing stage in some parts of the world.</p>
							<p><b>Storage of Information</b></p>
							<p>The Company does not rent, sell or share your personal or sensitive information and does not disclose any of your Personal Information to third parties unless you have granted the Company the permission to do so. However, we may pass your Personal Information to other third parties in the following scenarios:<br>
							i.	To help us process questions you may have about any Product displayed on the Site, service, registration or other inquiry you may have;<br>
							ii.	To confirm or correct what we know about you;<br>
							iii.	We may pass your Personal Information to our employees, contractors, suppliers and/or agents to administer the Services provided to you by us now or in the future;<br>
							iv.	To help us or law enforcement agencies prevent fraud, money laundering, terrorism and other crimes. Also, we may disclose your Personal Information to the police, regulatory bodies or legal advisers in connection with any alleged criminal offence or suspected breach of this Privacy Policy and or the breach of other terms and conditions otherwise relating to you or otherwise where required by law and we will co-operate with any law enforcement authorities or court order requesting or directing us to disclose the identity of or locate anyone breaching this Privacy Policy or otherwise for the prevention or detection of crime or the apprehension or prosecution of offenders.<br>
							v.	Assisting an agency in undertaking information for us;<br>
							vi.	If another organization is engaged by us to perform tasks on our behalf;<br>
							vii.	Compliance with an audit on our business;<br>
							viii.	If we sell all or any part of our business or merge with another company;<br>
							ix.	If it is necessary for legal proceedings and when we believe in good faith that any applicable law ,regulation, government, regulatory or other authority, agency or officer requires it or to protect the safety or security of users of the Site;<br>
							x.	If we use third party processors to administer and process your Personal Information for the purposes notified in the Privacy Policy, e.g. for hosting activities related to the use of the Site or Services; and<br>
							xi.	To obtain advice from third parties such as auditors or legal advisors.<br>
							In addition to the above, disclosures may also be made if it was clearly stated at the time of registration and, where required, if you have given permission for this. Generally, we will disclose only the information we consider reasonably necessary to disclose. Also, some general statistical information about the Site user base, traffic volumes and related matters may be passed on to reputable third parties but these details will not include information personally identifying you.
							</p>

							<p><b>Third Party Sites</b></p>
							<p>Please note that this Privacy Policy does not cover any third party sites to which we provide links in the Site, nor does it cover advertisers. They may have their own privacy policies and/or terms and conditions of use. The Site Owner provides third-party advertisements and only links to third party sites through the Site ("Linked Site"), but does not provide any Personal Information to these third-party sites or advertisers.<br>
							The Site Owner clarifies that the Linked Sites are operated by third parties and are not under control of or affiliation or association of the Site Owner unless specifically expressed by the Site Owner. The Site Owner is not responsible for any form of transmission, material received from any Linked Site. We are not liable and do not represent anything regarding the privacy practices and policies adopted by the Linked Sites and their owners/ operators. Also, we are not in a position to control or guarantee the accuracy, integrity, or quality of the information, data, text, software, music, sound, photographs, graphics, videos, messages or other relevant materials available on the Linked Sites.<br>
							Providing the Linked Sites on Site does not imply or convey any endorsement by the Site Owner in any manner or of the contents of the Linked Site. You are aware that the information you provide on the Linked Sites shall be governed by policies of the Linked Sites which you view. The Site Owner does not have power or authority to prevent misuse of your information through the Linked Sites or advertisers.<br>
							Linked Sites and advertisers may use technology to send the advertisements on the Site directly to your browser because of which the Linked Site or advertisers automatically receive your internet protocol address. They may use cookies, java script, web beacons and other technologies to measure the effectiveness of their advertisements and to personalize advertising content. The Site Owner has no access or control over cookies or other features of the Linked Sites or advertisers and are not governed by this Privacy Policy.</p>
							<p><b>Security Practices</b></p>
							<p>The Site Owner strives to ensure the security, integrity protection and privacy of your Personal Information against unauthorized access or unauthorized alteration, disclosure or destruction. We follow stringent security techniques and requirements for handling sensitive and Personal Information. These techniques and requirements are fully compliant with the guidelines set forth under law. Our servers are accessible only to authorized personnel. Your information logged under this Privacy Policy is shared with respective personnel only on need to know basis and/ or to provide the services you have requested. All representatives handling information under these provisions are under contractual confidentiality obligation with the Site Owner. While, we take every step to safeguard the confidentiality of your Personal Information, by using this Site, you agree and confirm that the Site Owner is not liable for any disclosure due to errors in transmission or unauthorized acts of third parties or Linked Sites.<br>
							Not with standing the foregoing, you must keep account details, including your username and password ("Account Information") confidential at all times, and should not reveal the same to any third parties. You must take appropriate security measures to prevent unauthorized disclosure of your Account Information (including logging out from your account at the end of each session), and you must notify us immediately if your Account Information becomes known to any unauthorized user. You are solely responsible for maintaining the confidentiality of your Account Information, and all activities that occur under your account (s). Any breach of this Privacy Policy by anyone to whom you disclose your account details, including your username and password will be treated as if the breach had been committed by you, and will not relieve you of your obligations under the Terms and Conditions.<br>
							Not with standing anything contained herein, the Company shall not be liable for any loss, damage or misuse of your Personal Information due to a force majeure event. A force majeure event for the purposes of this Privacy Policy shall mean any event that is beyond reasonable control of the Site Owner and shall include, without limitation, sabotage, fire, flood, explosion, acts of God, civil commotion, strikes or industrial action of any kind, riots, insurrection, war, acts of government, computer hacking, un authorised access to computer data and storage device, computer viruses breach of security and encryption or any other cause beyond the control of the Site Owner.</p>
							<p><b>Acceptance to terms</b></p>
							<p>By registering on the Site and using the Services you are deemed to have agreed to the terms of this Privacy Policy. This Privacy Policy should be at all times read along with the Terms and Conditions and the Policies of the Site. The Privacy Policy applies to all information, including Personal Information and Account Information.<br>
							By using the Services, you agree and acknowledge that your Personal Information may be transferred across national boundaries and stored and processed in any the country around the world. You acknowledge that in the process of providing the Services under the Site, some activities relating to handling of information collected under the Privacy Policy may be done by the Company’s trusted third party vendors or agents, web hosting providers, communication services, and web analytic providers.</p>
							<p><b>Changes to this policy</b></p>
							<p>We may change this Privacy Policy from time to time and we will post the latest version on the Site. You are expected to keep visiting the Site and reading the Terms and Conditions and the Policies including this Privacy Policy, the cancellation policy and the return policy at regular intervals to keep yourself updated.</p>
							<p><b>Amendments to Privacy Policy</b></p>
							<p>We reserve the right, in our sole discretion, to change, modify, add or delete portions of this Privacy Policy at any time without notice, and it is your responsibility to review this Privacy Policy from time to time, in order to keep track and take note of the changes. Your use of the Site following any amendment of this Privacy Policy will signify and constitute your consent to and acceptance of such revised this Privacy Policy. We will not file or store a copy of these terms for each interaction on transaction by you via the Site. We therefore recommend that you save a copy of this Privacy Policy for future reference, and ensure that such copies can be reliably verified as being effective (i.e. published on the Site) on a particular date.
							</p>
							<p><b>Contact details</b></p>
							<p>Thank you for reading our Privacy Policy and thank you for choosing our Site. If you have any questions about anything contained in the Privacy Policy, you can email us with any questions, queries or complaints at info@my-dream-wear.com. </p>
							<p><b>Disputes</b></p>
							<p>Any disputes over inter alia collection, storage and handling of Personal Information will be governed by this Privacy Policy, Terms and Conditions and by the laws of India and courts of Bangalore shall have exclusive jurisdiction. For any communication under this Privacy Policy please contact the Site Owner at info@my-dream-wear.com.</p>
							
						</div>
					</div><!-- .row -->
				</div><!-- .container -->
			</div><!-- .about-info -->
		</div><!-- .site-content -->
		
<?php require_once 'footer.php';?>