<?php require_once 'header-internal.php';?>

		<div id="content" class="site-content about-page">
			<div class="breadcrumb">
				<div class="container">
					<ul>
						<li><a href="index.php">Home</a></li>
						<li><span class="current">Terms & Conditions</span></li>
					</ul>
				</div><!-- .container -->
			</div><!-- .breadcrumb -->

			<div class="about-info">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<h2 class="heading-title">TERMS AND CONDITIONS</h2>
							<p>This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 which require the publishing of the rules and regulations governing the use and access of www.my-dream-wear.com</p>
							<h4>Introduction</h4><br>
							<p><strong>1.1</strong> These terms and conditions ("Terms and Conditions") and all applicable Policies (as defined below) which are herein incorporated by way of reference govern your rights and obligations as a User (defined below) of the Site (defined below) while accessing and using the Site and/or availing the Services (defined below), as may be rendered by PSom Technologies Private Limited, ("Site Owner") through the 'www.my-dream-wear.com' web portal (domain name– www.my-dream-wear.com) ("Site") to Users from time to time. Any reference to "you" or "User" or "User's" in these Terms and Conditions, means you the User of the Site, placing order for the products, displayed on the Site ("Products") for taking on rent such Product (s) or purchasing the Product (s) listed for sale on the Site, solely for personal use and/or accessing and using the Site Content (defined below) ("Services") in the manner as set out in these Terms and Conditions.</p>

							<p><strong>1.2</strong> As a User, your access to and use of the Site and/or the Services are conditional upon your acceptance of and continuous compliance with these Terms and Conditions at all times and all applicable Policies (as defined below). There is an explicit understanding that these Terms and Conditions and all the Policies shall be adhered to by you. By accessing, browsing and/or using the Site and/or availing any of the Services, you agree to be bound by these Terms and Conditions, the cancellation policy governing cancellation of an order for any Product placed by you ("Cancellation Policy"), the return policy governing the return of any Product rented to you ("Return Policy"), the privacy policy governing your access to the Site ("Privacy Policy"), other guidelines, policies, terms and conditions applicable to the Site and/or Services being provided by the Site Owner (collectively as "Policies"), as may be modified by the Site Owner from time to time at its own discretion, which shall be deemed to be incorporated in these Terms and Conditions by reference, unconditionally and at all times. Further, by accessing, browsing and/or using the Site and/or availing any of the Services, you explicitly agree to receive communications, in written and/or verbal form, from the Site Owner or its authorized representatives with regard to any matter relating to the Site, Products or the Services.</p>
							<p><strong>1.3</strong> The Site Owner shall have the sole right to change, modify, add or remove these Terms and Conditions or any or all of its Policies relating to the provisions of Services on the Site and access to the Site, at any time without any prior written notice or intimation to you. It is hereby clarified that each User shall be responsible for reviewing the Terms and Conditions and Policies on the Site periodically and keep themselves updated.</p>
							<h4>User Eligibility</h4><br>
							<p><strong>2.1</strong> The Services on the Site are only available to persons who are competent to enter into legally binding contracts under the Indian Contract Act, 1872 ("Contract Act"). Any person who shall be considered as incompetent to contract as per the provisions of the Contract Act including minors, un-discharged insolvents etc. are not eligible to use the Site ("User"). Any person using the Services on behalf of any other person/ proprietorship/ partnership/ firm/ company, represents and warrants that it is duly authorized by such person/ proprietorship/ partnership/ firm/ company being the User to accept the Terms and Conditions and the Policies and that such person has the authority to bind the User to these Terms and Conditions and all the Policies.</p>
							<h4>Sale and Renting of Products</h4><br>
							<p><strong>3.1</strong> The Site is a platform provided by the Site Owner to its Users, after registration of such User on the Site ("Registration") and their access to the Site through the account created on the Site by using the account details entered by such User ("Account Information"), to browse and take on rent the products displayed on the Site for a period of 3, 5 or 7 days starting from the date of delivery of the Product to the User ("Rental Period") or to purchase certain Products listed for sale on the Site subject to their availability. The Site Owner shall also provide such other services, including sale of Products, as may be included, removed and/or modified by the Site Owner from time to time.</p>

							<p><strong>3.2</strong> The Services and the Site are governed by these Terms and Conditions and all applicable Policies of the Site, as may be amended from time to time and shall be deemed to be incorporated in these Terms and Conditions by way of reference. Unless expressly stated otherwise, any new features that augment or enhance the current Services and the Site shall be subject to these Terms and Conditions and all the Policies.</p>
							<h4>Terms of Use</h4><br>
							<p><strong>4.1 Use of the Services</strong><br><strong>(a) Placing of orders by the User</strong><br>All orders shall be placed by a User by signing in on the Site using his/her Account Information. It is hereby clarified that the Site Owner shall have the sole right to accept or reject order placed for a Product by a User. Once an order is approved by the Site Owner, the User, placing such order shall receive a confirmation from the Site Owner in relation to the acceptance of his/her order ("Order"). The Products ordered will be delivered in accordance with Section 4.1 (c) (i) or Section 4.1 (c) (ii), as may be applicable, of these Terms and Conditions. It is explicitly agreed by you that you shall not avail the Services and/or access and use the Site for any other purposes except for your personal use. </p>
							<p>It is hereby clarified that the Products may appear different in color and style than as displayed on the Site. The size and measurements may vary depending on the Products.</p>
							<p><strong>(b) Restriction of Orders placed by the User and cancellation of Orders by the Site Owner</strong><br>The Site Owner may impose limitation or restriction on the maximum number of Orders placed by a single User for any of the Products listed on the Site through his/her account on the Site. The Site Owner further has the right to cancel any Order placed by the User or prohibit any User from taking on rent or purchasing any of the Products (s) listed for sale on the Site, for any reason, including but not limited to any likelihood that the User, as per Site Owner's discretion, will abuse the Services or any of the reasons or circumstances specified in the Cancellation Policy.</p>
							<p>The Site Owner shall deliver the Products ordered by a User including the size, color and design on or before the delivery date. It is hereby clarified that in the event a Product ordered by you is not available, the Site Owner shall take reasonable efforts to notify you of such unavailability and you shall have the right to order a replacement Product.</p>
							<p><strong>(c) Delivery and shipping of Products</strong><br>(i) Delivery of Orders placed for renting Products<br>The delivery of all Orders placed for renting any Product shall be made on the first day of the Rental Period for such Product. It is hereby clarified that the Site Owner shall undertake best efforts to ensure that the Products are delivered within the timelines specified, however the Site Owner shall not be liable for any delay in the delivery of the Products for reasons beyond the Site Owner's reasonable control.</p>

							<p>(ii) Delivery of Orders placed for purchasing the Products<br>
							The delivery of all Orders placed for purchasing the Products listed for sale on the Site shall be made within 30 days from the date of confirmation of an Order in accordance with Section 4.1 (a) above. It is hereby clarified that the Site Owner shall undertake best efforts to ensure that the Products are delivered within the timelines specified, however the Site Owner shall not be liable for any delay in the delivery of the Products for reasons beyond the Site Owner's reasonable control.<br>
							The User hereby agrees and acknowledges that for all Orders that are shipped and delivered by the Site Owner to the User, for either Section 4.1 (c) (i) or Section 4.1 (c) (ii) above, a delivery charge as specified on the Site may be payable by the User on account of delivery of the Product by the Site Owner ("Delivery Charges").<br>
							The shipping of the Orders for either Section 4.1 (c) (i) or Section 4.1 (c) (ii) above, is at the discretion of the Site Owner and shall generally be done through shipping partners, which are subject to change from time to time at the discretion of the Site Owner. It is clarified that the shipping and delivery of the Product will be initiated by the Site Owner only after the payment of Total Fee (defined below) or Sale Price (defined below), as the case maybe, by the User, to the satisfaction of the Site Owner.<br>
							The details pertaining to the shipping, delivery locations, the timelines for expected delivery and Delivery Charges, as may be applicable, for all Products are/may be specified on the Site.</p>
							<p><strong>(d) Payment by the User</strong><br>
							(i) Payment by User renting the Product(s)<br>
							It is clarified that the User shall pay rental fee as specified on the Site for every Order placed by such User ("Rental Fee") along with a security deposit being an amount equal to 100% to 150% of the Rental Fee ("Security Deposit") as applicable depending on garment rented and, if applicable, the Delivery Charges as may be displayed on the Site for each of the Products, from time to time (collectively "Total Fee"). It is clarified that the Total Fee is exclusive of any taxes, fees, duties or any other charges that the User is required to pay under the applicable law. All/any such tax or charge, as is payable by the User, shall be paid directly by the User. The Security Deposit shall be refunded to the User upon return of the Products ordered after making such deductions as maybe applicable in accordance with these Terms and Conditions, the Cancellation Policy and the Return Policy.<br>
							(ii) Payment by User purchasing the Product (s)<br>
							It is hereby clarified that the User shall pay the sale price as specified on the Site for every Order placed by such User to purchase a Product listed for sale on the Site ("Sale Price") and the Delivery Charges as may be displayed on the Site for each of the Products, if applicable, from time to time. It is clarified that the Sale Price is exclusive of any taxes, fees, duties or any other charges that the User is required to pay under the applicable law. All/any such tax or charge, as is payable by the User, shall be paid directly by the User.
							It is clarified that upon confirmation of an Order for either Section 4.1 (d) (i) or Section 4.1 (d) (ii) above, for a Product placed by a User, the Site Owner becomes authorized by the User to immediately charge the applicable Total Fee or Sale Price, as the case maybe, along with the Delivery Charges, if applicable, on the credit card/debit card of the User registered with the Site.<br>
							The User hereby undertakes and agrees that all payment details in relation to the credit card/debit card registered by the User on the Site and being used to place an Order for a Product, for either Section 4.1 (d) (i) or Section 4.1 (d) (ii) above, shall be valid and accurate. It is agreed that the Site Owner reserves the right to take, at its discretion, any legal action if the payment details are found to be invalid or inaccurate. It is clarified that you are responsible for maintaining confidentiality and security of the payment details and ensuring proper use of the credit card/debit card used by you in relation to the Services. It is clarified that the Site Owner shall not have any liability for any consequence arising out of unauthorized use of your credit card/debit card or the details thereof.</p>
							<p><strong>(e) Mode of Payment</strong><br>
							The payment of the Total Fee or the Sale Price, as the case maybe, in relation to the Order, shall be made by the User through any of the payment methods available on the Site. By making such payment, you explicitly authorize the Site Owner or its authorized representatives to charge the applicable Total Fee or Sale Price, as the case may be, or any other amounts, including damages and penalties, as may be due and payable by you to the Site Owner, through such payment method as may be availed by you. It is clarified that by placing an Order for any Product on the Site and authorizing the Site Owner to charge the Total Fee or the Sale Price, as the case may be, or any other amounts, including damages and penalties, as may be due and payable by you to the Site Owner, you are entering into a binding agreement with the Site Owner.</p>
							<p><strong>(f) Cancellation of the Order</strong><br>
							It is clarified that any request for cancellation of any order of Products (s) which is being rented, may be made by the User, subject to the cancellation policy as mentioned below . All the provisions of the Cancellation Policy shall govern such cancellation request made in relation to any Order placed by a User using the Site.</p>
							<p>This policy governs the cancellation of any Order for a Product placed by you as the user of the 'www.my-dream-wear.com' web portal ("Site") (domain name– www.my-dream-wear.com) ("Cancellation Policy") while renting a Product. It is here by clarified that Site Owner shall not accept the cancellation of Orders placed by a User for purchasing Products listed for sale on the Site and all such Orders shall be final and binding on the User placing such Orders. However, the Site Owner shall have the right to cancel an Order placed for purchase of Products listed for Sale in accordance with the terms specified below.<br>
							Any reference to "you" or "User" or "User's" in this Cancellation Policy, means you the User of the Site, renting the Products) displayed by (Company Name)(hereinafter referred to as "the Site Owner" "we" "us" or "our") solely for personal use and/or accessing and using the Site ("Services") in the manner as set out in the terms and conditions available at ("Terms and Conditions"). Each capitalized term not defined but used in this Cancellation Policy shall have the same meaning as ascribed to such term in the Terms and Conditions.<br>
							Please note that there may be certain orders, made by you for any of the Products displayed on the Site, which the Company may be unable to accept. We reserve the right, at our sole discretion, to refuse or cancel any Order for any reason. This Cancellation Policy identifies and sets out some situations that may result in cancellation of your Order for renting by the Site Owner.<br>
							Accordingly, an Order for the identified Product (s) may be cancelled by the Site Owner on occurrence of the following circumstances:<br>
							<ul>
								<li>the Product is no longer available or is temporarily unavailable;</li>
								<li>there are limited quantities of the identified Product (s) available for renting by the User registered on the Site and the same Product has been ordered by another User prior to your Order;</li>
								<li>a problem (s) is identified by the Company in relation to the payment made by the User for any Product displayed on the Site;</li>
								<li>inaccurate or insufficient Shipping Address or other detail (s) have been provided by the User at the time of placing an Order of any Product;</li>
								<li>the Product is requested to be delivered at a location where the Site Owner does not cater or is otherwise inaccessible; or</li>
								<li>there are inaccuracies, defect or errors in the identified Product (s) or its pricing information; or</li>
								<li>any malpractice or abuse is identified by the Site Owner on part of the User while placing any Order for a Product or any malpractice or abuse by the User of the Services rendered by the Site Owner.</li>
							</ul><br>
							We may also require additional verification or information before accepting any Order placed by you. We will contact you on the details provided by you during your registration on the Site, subject to the Terms and Conditions, if all or any portion of your Order is cancelled or if additional information is required by us to accept your Order. If your Order is cancelled after your credit card/debit card/account has been charged, the Total Fee or the Sale Price, as the case maybe, shall be reversed back in your card/debit card/account.
							</p>
							<p><strong>Cancellation request by the User in relation to renting of Products:</strong><br>
							In case of requests for Order cancellations, we reserve the right to accept or reject requests for Order cancellations for any reason. As part of usual business practice, if we receive a cancellation request by you in accordance with the cancellation terms specified below, the Site Owner shall cancel the Order and we shall issue a credit note in relation to the Rental Fee paid by you, however, it is clarified that you shall be liable to pay cancellation fee in the manner detailed below.<br>
							In the event you have requested for cancellation of the Order within 24 (Twenty Four) hours from the time of placing the Order and we have not shipped the Product, we shall issue a credit note for the Rental Fee and 100% of delivery charges, if applicable, subject to this Cancellation Policy. Further, 100% of the Security Deposit shall be refunded to you.<br>
							In the event you have requested for cancellation of the Order at least 30 (Thirty) days prior to the scheduled delivery date, you will be eligible for a credit note for 80% of the Rental Fee and 100% of delivery charges, if applicable. However, 100% of the Security Deposit shall be refunded to you.<br>
							In the event you have requested for cancellation of the Order at least 10 (Ten) days prior to the scheduled delivery date, you will not be eligible for any refund and your request for cancellation of the Order shall be deemed invalid. However, 100% of the Security Deposit shall be refunded to you.<br>
							The time at which any Order is made by you for any of the Product (s) shall be recorded by the Site Owner at its sole discretion and such time shall not be disputed by you.<br>
							The User agrees not to dispute the decision made by the Site Owner in relation to the determination of the applicable Cancellation Fee and accept the Site Owner's decision made in response to any cancellation request made by the User.<br>
							In case you want to cancel an Order please send a written request at the following email address – info@my-dream-wear.com.<br>
							Any dispute regarding a cancellation request will be governed by this Cancellation Policy and by the laws of India and courts of Bangalore shall have exclusive jurisdiction.</p>
							<p><strong>(g) Receipt of the Product</strong><br>
							The Products shall be shipped to the shipping address provided by you at the time of placing an Order ("Shipping Address"). It is clarified that the Shipping Address provided by you shall be accurate and secured and that the Site Owner shall not be liable for any delay in delivery if such Shipping Address is found to be inaccurate or insecure at the time of delivery of the Product. In the event the Shipping Address is found to be inaccurate or insecure, additional delivery charges, as may be computed at the sole discretion of the Site Owner, shall be paid by you.</p>
							<p><strong>(h) Use of the Products (applicable for Users renting the Products)</strong><br>
							All Products delivered pursuant an Order are professionally dry cleaned prior to delivery and ready to wear upon receipt of delivery. The Site Owners take all reasonable care to dry clean and inspect each Product prior to delivery but use of the Product is at your own risk and the Site Owner shall not be liable for any health related complaints in relation to the Products. Upon delivery of the Product by the Site Owner at the Shipping Address provided by you, you shall have the entire responsibility in relation to the use, maintenance, and safety of the Product ordered by you and delivered by the Site Owner to you.<br>
							You shall be solely responsible for protecting the Product delivered to you from any loss, destruction or damage caused due to any reason, including but not limited to theft, fire stains, other stains, alterations, tearing, rubbing-off ("Substantial Damage"). You shall further be responsible for protecting the Product delivered to you from any loss which may result in any form of diminution in the Product's commercial value ("Major Loss"). You shall be responsible for handling the Products, during the Rental Period, with the same extent of care and precaution as you will exercise with regard to any of your personal properties.<br>
							If any damage is done to the Product which has the effect of mere normal wear and tear as per the determination of the Site Owner, you shall not be liable for such extent of damage to the Product. However, if the Site Owner determines that a Substantial Damage has been done to the Product on your part, an additional charge of upto 25% of the retail value of such Product, shall be payable by you on account of such Substantial Damage to the Product. It is clarified that such amount, as is required to be paid by you on account of any Substantial Damage, shall be determined at the sole and absolute discretion of the Site Owner.<br>
							In the event the Site Owner determines that a Major Loss has been done to the Product on your part, an additional charge of upto100% of the retail value of such Product, as determined by the Site Owner, shall be payable by you on account of such Major Loss.<br>
							You hereby explicitly agree to such levy of additional charge on account of any Substantial Damage or Major Loss as may be determined by the Site Owner to have caused to the Product on your part while using such Product. It is clarified that in the event of any Substantial Damage or Major Loss caused to the Product during the Rental Period, the Site Owner becomes authorized to adjust the penalties for such Substantial Damage or Major Loss, as specified above, against the Security Deposit paid by you. In the event the penalty for such Substantial Damage or Major Loss, as specified above, is an amount higher than the Security Deposit, the Site Owner is hereby authorized by the User to immediately charge the User the penalties for the balance of such Substantial Damage or Major Loss, as per the sole and absolute determination of the Site Owner. Further, in the event the penalty for such Substantial Damage or Major Loss, as specified above, is an amount lower than the Security Deposit, the balance of the Security Deposit shall be refunded to you by the Site Owner in accordance with these Terms and Conditions.<br>
							In the event the Product delivered to you does not fit you then you shall notify the Site Owner within 4 hours of delivery of the Product by email address: info@my-dream-wear.com and the Product shall be picked up by the Site Owner from the Shipping Address on the date of receipt of such intimation in the manner specified above and in accordance with the terms of the Return Policy. The time at which you notify the Site Owner shall be recorded by the Site Owner at its sole discretion and such time shall not be disputed by you. In such an event the Site Owner shall issue you a credit note for the Rental Fee excluding the Delivery Charges, if applicable, for renting of a Product at a future date subject to the satisfaction of the Site Owner that the Product has not been worn or used.</p>
							<p><strong>(i) Return of the Product (applicable only for Users renting the Products)</strong><br>
							It is clarified that you shall return the Products (s) ordered from the Site, in accordance with the terms of the Return Policy as mentioned below. All the provisions of the Return Policy shall govern the Product as displayed on the Site and delivered to you by the Site Owner in pursuance to your Order for renting such Product. It is clarified that in the event of any delay on the part of the User to return the Product within the stipulated period, the Site Owner is hereby authorized by the User to immediately charge the User the penalties for such delay, as per the terms and conditions prescribed in the Return Policy.<br>
							It is hereby clarified that the Site Owner shall not accept any return in case of Products being purchased by a User using the Site and the Site Owner shall not be liable for any loss incurred by a User if the Product purchased does not fit the User or is it appears different in color and style than as displayed on the Site.<br>
							This return policy governs the return of any Product (defined below) ordered by you, as the user of the 'www.my-dream-wear.com' web portal ("Site") (domain name – www.my-dream-wear.com) ("Return Policy"). Any reference to "you" or "User" or "User's" in this Return Policy, means you the User of the Site, ordering and renting the Products (defined below) displayed by (Company Name) (hereinafter referred to as "the Site Owner" "we" "us" or "our") solely for your personal use and/or accessing and using the Site ("Services") in the manner as set out in the terms and conditions available at ("Terms and Conditions"). Each capitalized term not defined but used in this Return Policy shall have the same meaning as ascribed to such term in the Terms and Conditions.<br>

							Please note that for all the Orders, made by you for renting any of the Products displayed on the Site, you agree that you shall return such Product, in a satisfactory condition as specified herein and in the Terms and Conditions, to the Site Owner in the manner as set out in this Return Policy. It is here by clarified that this Return Policy is not applicable for Products that are being purchased by you through the Site.<br>
							You hereby agree and acknowledge that you shall be solely responsible to return the Products delivered to you within a period of 3, 5 or 7 (as per the period mentioned at the time of renting) days from the date of delivery ("Return Date") in a satisfactory condition and subject to the Terms and Conditions. Further, you agree that the Site Owner is entitled to and authorized, to charge the applicable late fee as detailed below ("Late Fee") in the event you fail to return the Product to the Site Owner in the manner set out below in this Return Policy, before the expiry of the Return Date.<br>
							i.	In the event the Product is not returned within 1 (One) day from the Return Date, the Site Owner shall have the right to charge you a Late Fee equivalent to an amount of 25% of the Rental Fee, plus all applicable taxes.<br>
							ii.	Thereafter, in the eventuality that the Product is not returned within 2 (Two) to 7 (Seven) days from the Return Date, the Site Owner shall have the right to charge you a Late Fee equivalent to an amount of 50% of the Rental Fee per day, plus all applicable taxes for each day of delay in returning the Product.<br>
							iii.	Thereafter, in the eventuality that the Product is not returned within 8 (Eight) days from the Return Date, the Site Owner shall have the right to charge you a Late Fee equivalent to an amount of 100% of the retail price of the Product, plus all applicable taxes, less the penalty amount already paid by you on account of delay in return of the Products as Late Fee, calculated in the manner specified in sub-clauses (i) and (ii) above.<br>
							It is hereby clarified that the Late Fee chargeable by the Site Owner shall be in addition to the Rental Fee payable by you for each Product, ordered and delivered to you by the Site Owner and any additional payment due and payable on account of any material damage done to the Product by you at the time of using such Product in accordance with the terms of the Terms and Conditions.<br>
							The Site Owner shall have the right to adjust the Security Deposit being equivalent to 100% to 150% of the Rental Fee of the Product given by you in accordance with the Terms and Conditions, against the Late Fee payable by you in accordance with the terms of this Return Policy. In the event the amount of Late Fee payable by you is higher than the Security Deposit, you hereby authorise the Site Owner to immediately charge the balance Late Fee, on the credit card/debit card of the User registered with the Site. Further, in the event the Late Fee payable by you is an amount lower than the Security Deposit, the Site Owner shall refund the balance Security Deposit in accordance with the Terms and Conditions.<br>
							You hereby agree and acknowledge that you shall be solely liable for returning the Product in the same conditions (excluding normal wear and tear) as the Product was delivered to you. It is hereby clarified that you shall be liable for all costs incurred by the Site Owner in relation to any Substantial Damage or Major Loss to the Product caused by you. The cost assessment of the Site Owner in this regard shall be final and binding on the User. The Site Owner shall have the right to deduct such costs for Substantial Damage or Major Loss, as the case maybe, from the Security Deposit provided by you.<br>
							At the time of returning the Product, you are required to package the Product in the original packing in which it was delivered to you or any return packing provided to you by the Site Owner at the time of delivery of the Product. Kindly ensure that you seal the package properly.<br>
							It is further agreed that the Product shall be returned in a safe and acceptable manner, only to the person designated by the Site Owner, who shall pick up the Product from your Shipping Address on or before the Return Date, as per your instructions.<br>
							You hereby explicitly agree not to dispute the decision made by the Site Owner in relation to the determination of a material damage done to the Product during its delivery on your part and/or any Substantial Damage or Major Loss in accordance with the Terms and Conditions.<br>
							Any dispute regarding return of any Product or any of the terms of this Return Policy will be governed by this Return Policy and by the laws of India and courts of Bangalore shall have exclusive jurisdiction.</p>
							<p><strong>(j) Delay in Service</strong><br>
							It is clarified that the Services and/or the Site may involve deficiencies, including but not limited to omissions, interruptions, loss of data, and inaccuracies, delay in delivery and the Site Owner shall not have any liability on occurrence of such deficiencies in the operation of the Services and/or the Site, including but not limited to any omission, interruption, loss of data, in accuracy and delay in delivery that may be experienced by you at the time of browsing or ordering any Product displayed on the Site. The Site Owner hereby disclaims any liability or responsibility for such deficiencies. The Site Owner shall put best efforts to ensure smooth operation of the Service and/or the Site however, it does not guarantee against the possibility of any of the identified deficiencies in the Services and/or the Site. You acknowledge that the Site Owner may direct any precautions to you for ensuring that there is no breach of security and integrity of the Site and on such directions you shall provide the necessary support to the Site Owner. The Site Owner disclaims any responsibility for a loss that may be incurred by you due to any failed or incomplete transaction on the Site.</p>
							<p><strong>4.2 Content on the Site</strong><br>
							a. It is hereby clarified that the Services provided to you may involve references to or links of any third-party or its products, services or other content ("Third-Party Content"). You acknowledge that the Site Owner is not liable for any such Third-Party Content as may be displayed on the Site or that you may be re-directed to while accessing the Site and/or availing the Services. It is further clarified that the Site Owner shall not be liable for any persons who may have provided such Third-Party Content. The Third-Party Content displayed on the Site or re-directed to by the Site does not suggest that the Site Owner has endorsed such Third-Party Content or provider of the Third-Party Content. It is clarified that the Site Owner shall not be liable for any privacy practices of a third-party providing such Third-Party Content.<br>
							b. Site Owner is partnering with any of the designers specified on this Site. Each of the Products listed on this Site are owned by designer. The copyright and the design right of the Products listed on this Site are owned by the specific designer, as the case may be, and the Site Owner does not own and/or have any interest in the copyright and design rights associated with any of the Product. All photographs used on this Site are the copyright of the Site Owner. The Site Owner has undertaken its best efforts to ensure that the Products listed on this Site are authentic and original works of the specified designer.<br>
							c. It is hereby clarified that any content made available by the Site Owner to you while providing the Services or access to the Site, including but not limited to specification of any the Products, images of the Product or any comments or reviews by other Users on the Site (collectively as "Site Content") is available on "as is" and "as available" basis and is displayed solely for informational purposes. It is clarified that the Site Content made available by the Site Owner to you does not constitute and shall not be relied on by you as any information that substitutes professional advice or service (s). It is further clarified that any update of or modification to the Site Content shall be done at the sole discretion of the Site Owner. The use of the Site and/or the Services shall be governed by the terms of these Terms and Conditions and the Policies as amended and updated. The User hereby agrees and acknowledges that the Site Owner is not liable for any non-disclosure or incomplete disclosure of any information in relation to the Products displayed on the Site and/or the Services provided by the Site Owner.<br>
							d. If any information is made available by you to the Site Owner or uploaded on the Site, including but not limited to images, reviews pertaining to your use of the Product (s) or any other materials in relation to the Services ("User Content"), the Site Owner becomes entitled to a perpetual, non-exclusive, royalty-free, irrevocable and transferable license to use, reproduce, transfer, display, amend or exploit in any other manner the User Content in any media format at the discretion of the Site Owner. You hereby explicitly agree and accept that the Site Owner has the sole and absolute discretion to remove any User Content uploaded by you on the Site or restrict the publication of any User Content on the Site, for any reason whatsoever. You hereby explicitly agree that the Site Owner may use the User Content for any purpose as it may think fit, including but not limited to promotion, marketing, and advertisement of the Services and/or the Site without your consent and without any payment by the Site Owner in relation to such use of the User Content. It is clarified that you are responsible to ensure that the User Content submitted or uploaded by you is in consonance with these Terms and Conditions. It is further clarified that the Site Owner shall not be liable for any disclosure, use, modification or transfer of the User Content.<br>
							e. The User undertakes and agrees not to host, display, upload, modify, publish, transmit, update or share any User Content including any information, image or graphic that:<br>
							i.	is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, libelous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever;<br>
							ii.	harm minors in any way;<br>
							iii.	infringes any patent, trademark, copyright or other proprietary rights;<br>
							iv.	violates any law for the time being in force;<br>
							v.	deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;<br>
							vi.	impersonate another person;<br>
							vii.	contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource;<br>
							viii.	threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting any other nation.<br>
							f. You agree that you shall, at all times, comply with the requirements of the Information Technology Act, 2000 ("IT Act") as also rules, regulations, guidelines, bye laws and notifications made there under while assessing the Site Content or submitting to the Site Owner or uploading on the Site any User Content. You further unequivocally declare that in case of any violation of any provisions of the IT Act and/or rules, regulations, guidelines, byelaws and notifications made there under, you shall be solely responsible, at your sole cost and expenses for all acts, deeds and things and that you alone shall be liable for civil and criminal liability there under or under any other law for the time being in force.
							</p>
							<p><strong>4.3 Account created on the Site</strong><br>
							(a) It is clarified that you will be solely responsible or liable for any unauthorized use of the account created by you on Registration on the Site after entering the Account Information. The Site Owner disclaims any responsibility or liability for an unauthorized disclosure of the Account Information and/or any other details pertaining to your account created on the Site. It is clarified that you shall notify the Site Owner of any unauthorized use of the account or the Account Information or breach of security. It is agreed that you shall be solely liable for any loss that may be caused due to such unauthorized use of the account or the Account Information or any other act that results from your failure of keeping the account and the Account Information secure and confidential. It is further clarified that you are solely liable for any charges that may be incurred while using the account created on the Site. It is clarified that you are responsible for entering accurate Account Information and updating the Account Information. It is explicitly agreed that the Site Owner reserves the right to terminate, at its discretion, the account created by you on the Site, if the Account Information is found as untrue, inaccurate, outdated, incomplete or inconsistent.
							</p>
							<p><strong>4.4 Service license</strong><br>
							(a) It is clarified that the Site Owner has granted you a limited, non-transferable, non-exclusive and revocable right, which is subject to these Terms and Conditions and all the Policies referred herein, to access and use the Services and/or the Site solely for your personal and non-commercial use. It is clarified that the Site Owner reserves an absolute right to restrict or prohibit your access to or availing the Services and/or the Site, at its sole discretion and without assigning any reason thereto.<br>
							(b) You, while accessing and using the Site and/or the Services, shall duly comply with all requirements specified in these Terms and Conditions and all other applicable Policies, including but not limited to the Privacy Policy, Return Policy and Cancellation Policy, as may be amended from time to time by the Site Owner.
							</p>
							<p><strong>4.5 Claims of Copyright infringement</strong><br>
							If you are of the opinion that any of the Products displayed on the Site infringes your copyright, a request may be made to the Site Owner, on the details provided on the Site, for removal of the said Product from the Site. The request shall be accompanied with a statement identifying the Product which is alleged to have infringed your copyright and a statement declaring that the claims made by you are in good faith and accurate. On the receipt of such request and verification of the alleged infringement, the Site Owner may, at its sole discretion, remove such Product from the Site or take any other action as it may deem fit.
							</p>
							<p><strong>4.6 Indemnity</strong><br>
							(a) You hereby agree that you shall keep the Site Owner, its affiliates and group companies, successors, assigns and its respective officers, directors and agents, shareholders, representatives indemnified and defend and hold harmless from and against all actions, proceedings, claims, liabilities (including statutory liability), penalties, demands and costs (including without limitation, legal costs), awards, damages, losses and/or expenses however arising directly or indirectly, including but not limited to, as a result of:<br>
							i.	any breach or non-performance by you of any of your undertakings, warranties, covenants, declarations or obligations under these Terms and Conditions; or<br>
							ii.	any hacking or lapse in security of the Site or the data on the Site; or<br>
							iii.	any act, deed, omission or non-performance on your part which renders the transaction undertaken through the Site invalid.<br>
							(b) The indemnities provided herein and provisions making reference to the indemnities shall survive the termination of these Terms and Conditions and all the Policies, including but not limited to the Privacy Policy, Cancellation Policy and Return Policy.
							</p>
							<p><strong>4.7 Limitation of liability</strong><br>
							(a) Notwithstanding anything stated under these Terms and Conditions and the Policies, in the unlikely and rare event, you hereby acknowledge that the Site Owner's aggregate liability with respect to the Services and/or the Site shall be limited to and not exceed, in any event, the sum equivalent to the Rental Fee or Sale Price, as the case maybe, of your single, most recent transaction and shall be as per these Terms and Conditions (excluding the Delivery Charges, if applicable).<br>
							(b) You hereby agree and confirm that the sole and exclusive responsibility and obligation of the Site Owner is to ensure that the Services are being provided in compliance of all applicable laws, rules and regulations.</p>
							<p><strong>4.8 Disclaimer of warranties and liabilities</strong><br>
							(a) It is hereby clarified that all Products displayed on the Site and made available to you are provided on an 'as is' and 'as available' basis, without any representations and warranties, express or implied by the Site Owner. The Site Owner does not make any representations pertaining to the information or content, including but not limited to the Site Content or Products displayed on the Site and made available to a User through the Site.</p>
							<p><strong>4.9 Intellectual Property</strong><br>
							(a) You acknowledge that the Site shall provide information pertaining to other User's availing the Services and information pertaining to the Site Owner, in addition to the Site Content. You hereby agree that you shall not copy, modify or distribute or misuse any information provided on the Site for any purpose, including but not limited to your personal use or gain. You acknowledge that the Site Owner is the sole and rightful owner of the Intellectual Property and you agree not to register, use or file in your own name or in the name of any other person or company any trademarks same or similar or resembling, in any manner, the Intellectual Property and not to associate the Intellectual Property with your own business, except for the purpose as specified in these Terms and Conditions and all the Policies. In this regard "Intellectual Property" shall mean any and all property in any name, signature, word, letter, numeral or any combination thereof, trademark, brand name, service mark, trade name, copyright, design, logo, know-how, trade secrets, photographs/images of the Products displayed on the Site whether registered or not, belonging to the Site Owner.
							</p>
							<p><strong>4.10 Confidentiality</strong><br>
							(a) You hereby agree that you shall keep confidential and not disclose to any third-party, all/any Confidential Information pertaining to the Services, the Site or any transaction undertaken on the Site, including but not limited to the Site Content that you may receive or access while browsing or ordering a Product, or transacting on the Site. Breach by you of this Section and terms of the Privacy Policy, will be considered a material breach and result in immediate discontinuation of the Services and your access to the Site provided by the Site Owner to you. You hereby acknowledge and agree that a breach of the confidentiality provisions here in and under any of the Policies by you shall cause immediate termination of the Services and/or access to the Site and appropriate legal action being initiated against you by the Site Owner.<br>
							(b) "Confidential Information" shall mean all the information of a confidential nature disclosed (whether in writing, verbally or by any other means and whether directly or indirectly) by the Site Owner to you whether before or after the date of these Terms and Conditions. You shall not, where applicable and during the pendency of these Terms and Conditions or at any time after these Terms and Conditions and the Policies expire or terminate, divulge or use any Confidential Information for the benefit of any other person, corporation, partnership, proprietorship, association, or other entity, nor will you, directly or indirectly, permit the disclosure of any Confidential Information or aid any third party to imitate any Confidential Information.</p>
							<p><strong>4.11 Termination</strong><br>
							(a) The Site Owner may terminate these Terms and Conditions, the Policies, Services and/or access to the Site hereunder for any reason, including but not limited for reasons of breach, by you, of these Terms and Conditions or all/any of the Policies, including the Privacy Policy, Cancellation Policy and Return Policy. Your sole right to terminate these Terms and Conditions and the Policies, including the Cancellation Policy, Return Policy and Privacy Policy is by not using the Site and/or Services and deleting your account on the Site.</p>
							<p><strong>4.12 Consequences of termination</strong><br>
							(a) It is clarified that the termination of these Terms and Conditions, the Policies, the Services and/or access to the Site shall not affect any liabilities incurred by you prior to such termination or for acts performed during the pendency of these Terms and Conditions and the Policies which may result in a dispute post-termination of these Terms and Conditions, nor any provision expressed to survive or to be effective on termination and the obligations set out in this Section shall remain in full force and effect notwithstanding the termination.<br>
							(b) All Products taken on rent and in possession of a User shall be returned to the Site Owner immediately upon termination of these Terms and Conditions. Further any materials issued by the Site Owner from time to time in respect of these Terms and Conditions and/or Policies, whether in respect of accessing the Site or renting a Product or otherwise, shall be returned immediately to the Site Owner on termination of these Terms and Conditions, the Policies, the Services and/or access to the Site.
							</p>
							<h4>General Provisions</h4><br>
							<p><b>5.1</b> It is clarified that if you do not agree to the applicability of any of the Terms and Conditions and the Policies contained herein, including the Privacy Policy, Cancellation Policy and Return Policy on the Site, then the only remedy you shall have will be to not use the Services and discontinue using your account created on the Site. However, till such time that you use the Site and avail the Services it shall be deemed that you agree to and shall continue to adhere and abide by the Terms and Conditions and all the Policies.<br>
							<b>5.2</b> You will be required to provide a valid phone number, credit card/debit card details, accurate and full Shipping Address in order to avail the Services provided by the Site Owner, including and not limited to placing orders for renting or purchasing the Products displayed on the Site. By registering your phone number with the Site Owner, you consent to be contacted by the Site Owner via phone calls and/or SMS notifications, in case of any Order or shipment or delivery related updates.<br>
							<b>5.3</b> You acknowledge you shall be aware of all the terms of these Terms and Conditions and all the Policies before placing an Order for a Product displayed on the Site. You further acknowledge that the Services are being provided by the Site Owner as an independent contractor, and the Site Owner is in no manner acting as your agent.<br>
							<b>5.4</b> The Site Owner may assign, in whole or in part, the benefits or obligations of these Terms and Conditions and any/all the Policies to its associates or affiliates or other group company or any other company, in circumstances, including but not limited to pursuant to a restructuring or re-organization or demerger of its organization or operations causing a change in management or something of the nature. The Site Owner shall not require your approval or consent for an assignment of the benefits or obligations under these Terms and Condition, the Polices or any other policy in relation to the Services and/or the Site. It will be at the discretion of the Site Owner to decide if you should be intimated of such assignment. However, you shall not assign, in whole or in part, the benefits or obligations of these Terms and Conditions, the Policies or other policy in relation to the Services and/or the Site, without the prior written permission of the Site Owner.<br>
							<b>5.5</b> The Site Owner shall not be liable for its failure to perform under these Terms and Conditions and the Policies as a result of occurrence of any force majeure events like acts of God, fire, wars, sabotage, civil unrest, labour unrest, action of statutory authorities or local or central governments, change in laws, rules and regulations, affecting the performance of the Site Owner.<br>
							<b>5.6</b> Any dispute or claim relating to it, its enforceability or its termination under these Terms and Conditions and the Policies shall be governed by the Arbitration and Conciliation Act, 1996 by a sole arbitrator appointed by the Site Owner. The arbitration proceedings shall be held in English language at New Delhi. The courts at New Delhi shall have exclusive jurisdiction over any disputes relating to the subject matter herein.<br>
							<b>5.7</b> Unless otherwise expressly stated, failure to exercise or delay in exercising a right or remedy, hereunder shall not constitute a waiver of the right or remedy or a waiver of any other rights or remedies, and no single or partial exercise of any right or remedy, hereunder shall prevent any further exercise of the right or remedy or the exercise of any other right or remedy.<br>
							<b>5.8</b> The terms and provisions of these Terms and Conditions and the Policies, as identified herein and by their nature or content, are intended to survive the performance hereof and shall so survive termination.<br>
							<b>5.9</b> If any provision of these Terms and Conditions and/or the Policies, hereunder becomes, in whole or in part, invalid or unenforceable but would be valid or enforceable if some part of that provision was deleted, that provision shall apply with such deletions as may be necessary to make it valid. If any court/tribunal of competent jurisdiction holds any of the provisions, hereunder unlawful or otherwise ineffective, the remainder shall remain in full force and the unlawful or otherwise ineffective provision shall be substituted by a new provision reflecting the intent of the provision so substituted.<br>
							<b>5.10</b> You warrant that you shall not directly or indirectly solicit for employment, nor offer employment to, nor enter into any contract of services with any person employed by the Site Owner.<br>
							<b>5.11</b> It is agreed and clarified that the arrangement set out by these Terms and Conditions and the Policies between you and the Site Owner is on a non-exclusive basis.<br>
							<b>5.12</b> All notices, requests, demands, waivers and other communications required or permitted to be given hereunder shall be sent to info@my-dream-wear.com, if to the Site Owner, if to you, it shall be to the email address and/or postal address registered with the Site Owner.<br>
							<b>5.13</b> These Terms and Conditions and Policies may be varied, amended or modified by the Site Owner at any time and at its sole discretion without any intimation to you. The last amended version shall be available on the Site at all times. It is clarified that you shall be responsible for reviewing the Terms and Conditions and Policies on the Site periodically and keep updated.</p>
							<p>You have read and understood the above Terms and Conditions. You agree that by accessing the Site and/or availing the Services you hereby accept the Terms and Conditions and the Policies displayed on the Site and further agree to be bound by these Terms and Conditions and the Policies as may be modified by the Site Owner from time to time. You further agree that the Services and the Site the access to which is being provided to you by the Site Owner is subject to change.</p>
						</div>
					</div><!-- .row -->
				</div><!-- .container -->
			</div><!-- .about-info -->
		</div><!-- .site-content -->
		
<?php require_once 'footer.php';?>